### ISSUE TITLE
Merging L5 support from fork

### ISSUE THREAD

**Issue by Lednerb** [sunspikes/clamav-validator#1]
@sunspikes 
@lenrsmith implemented support for Laravel 5 and it seems to work with the new Laravel 5.1 LTS version (see the forks list).

Pls merge his changes to your repo so the support for L5 is available on [packalyst](http://packalyst.com/packages/package/sunspikes/clamav-validator) and  [packagist](https://packagist.org/packages/sunspikes/clamav-validator)

**Comment by sunspikes** [comment]
Hi @Lednerb thank you. Done.

**Comment by Lednerb** [comment]
:+1:

**Comment by lenrsmith** [comment]
Sweet!
