### ISSUE TITLE
Eicar test signature and test sources folder

### ISSUE THREAD

**Issue by joelyuk** [sunspikes/clamav-validator#10]
Hello,

We've been trying to use your package for ClamAV scanning in Laravel - which has been fantastic in helping us scan files automatically - but we've run into a few issues with the Eicar test signature being directly included in the package source.

This is often tripping out AV scanners both on developer machines when the package is pulled in and is likely to cause some frustration with IT security types receiving alerts for the test signature, and also triggering alerts on production servers when AV scanning and the package is deployed as part of a site.

Could you possibly consider perhaps exporting the package with the tests folder excluded (e.g. as Laravel does here in a .gitattributes with its tests folder - https://github.com/laravel/framework/blob/5.5/.gitattributes) so that the Eicar test signature isn't pulled down onto the machine when we use the package?

Open to any other suggestions also to help prevent the Eicar test signature from causing any false positives too.

Thanks for your help!

**Comment by sunspikes** [comment]
Hello @joelyuk,

Indeed! thank you so much for pointing this out. I should have done this earlier.

I've updated the gitattributes and bumped the v1.3 release.

Cheers!

**Comment by joelyuk** [comment]
Fantastic, thanks @sunspikes! 

And thank you for sorting that out so quickly too!
