### ISSUE TITLE
Debian 9

### ISSUE THREAD

**Issue by benrolfe** [sunspikes/clamav-validator#16]
I've installed **Clamav** using these Docker commands:

```
RUN freshclam
RUN service clamav-daemon start
```

However my Laravel code can't find the socket, even though I've told it to look at `/var/run/clamav/clamd.ctl`.

Laravel error: `Socket operation failed: Connection refused (SOCKET_ECONNREFUSED)`

Any suggestions?

**Comment by sunspikes** [comment]
Sorry that i missed this, Can you please check if the clamav daemon has started?

In Debian i think the `service` command is not available unless you install `sysvinit-utils`

So i think it should be,

`RUN systemctl start clamav-daemon` instead of `RUN service clamav-daemon start`

**Comment by sunspikes** [comment]
With the new release you can configure the clamav parameters yourself: https://github.com/sunspikes/clamav-validator/blob/master/config/clamav.php

**Comment by redLineColor** [comment]
Hello, i have the same problem on Ubuntu 18.04
I Installed using:
sudo apt-get update && sudo apt-get install -y clamav-daemon
sudo systemctl enable --now clamav-daemon clamav-freshclam

On homestead with Ubuntu 18.04 is working. any ideas why is not working on real server?

**Comment by supratimneogi** [comment]
Please wait i will give you solution tomorrow.
