### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by spike-isao** [sunspikes/clamav-validator#26]
Hi,

Could you please update this package's dependency to Laravel 6.0. Current this package requires illuminate/validation ^5.0.
Best regards,

**Comment by sunspikes** [comment]
Thanks for letting me know, I will address this in 2.x release

**Comment by spike-isao** [comment]
Thanks a lot!

**Comment by sunspikes** [comment]
Its here: https://github.com/sunspikes/clamav-validator/releases/tag/v2.0.0
