### ISSUE TITLE
Performance when scanning

### ISSUE THREAD

**Issue by alphametric** [sunspikes/clamav-validator#31]
This is not an issue as such, but I’m just curious... how long does it take to scan the uploaded file? I’m wondering about the performance impact. 

Thanks!

**Comment by sunspikes** [comment]
The library creates a file stream for the candidate file and pass through clamav daemon as an `INSTREAM` (https://linux.die.net/man/8/clamd) and reads the response.

For the files i have tested (<20 MB) this happens pretty quick (~1 second). I have not tested with very large files, but clamav scanner works pretty fast for files, but i think it depends on the file and network I/O time for larger files.

**Comment by alphametric** [comment]
Nice. Thanks for the info :)
