### ISSUE TITLE
ClamAV scanner client failed with error "Socket operation failed: Connection reset by peer (SOCKET_ECONNRESET)"

### ISSUE THREAD

**Issue by felixprawira** [sunspikes/clamav-validator#35]
Hi, I tried to upload file which size 400MB, then I got this error.
If I upload lower size files, there's no problem.
What should I change to avoid this error?

**Comment by firasabb** [comment]
To anyone who is having this issue: 

- Check the log (you can find it in /var/log/clamav/ if you are using linux)

- You may have to modify those:
`StreamMaxLength
MaxScanSize 
MaxFileSize`

You can read more about the configuration here: https://manpages.debian.org/unstable/clamav-daemon/clamd.conf.5.en.html
