### ISSUE TITLE
It does not support multiple files in the same input

### ISSUE THREAD

**Issue by mcolominas** [sunspikes/clamav-validator#38]
When I have an input that allows the upload of a single file it works fine, but when the input is multiple, it gives an error:
ErrorException: is_readable() expects parameter 1 to be a valid path, array given in /absolute/path/vendor/sunspikes/clamav-validator/src/ClamavValidator/ClamavValidator.php:52

**Comment by steve-mb** [comment]
I had a similar issue but had forgotten to check for multiple files.  
'file.*' => 'max:5120|clamav',
