### ISSUE TITLE
Method [validateClamav] does not exist.

### ISSUE THREAD

**Issue by smaameri** [sunspikes/clamav-validator#39]
Am using Laravel 5.5, and get this error when trying to use clamav as a validator. I have installed the package, and added it to app/config.php as a provider.

**Comment by smaameri** [comment]
Issue was solved by running **php artisan config:cache**. Probably installation instructions should be updated to include this.

**Comment by furkankadioglu** [comment]
Same here (using Lumen 6.x) 😞
