### ISSUE TITLE
Timeout error on clamav validator

### ISSUE THREAD

**Issue by rupalikombade** [sunspikes/clamav-validator#45]
We are facing intermittent issue. We are getting error as below.

**ClamAV scanner client failed with error "Timeout waiting to read response"** 

Any idea what is reason behind it ? sometime its working fine and sometime we are getting above error.

**Comment by khyatiacharya91** [comment]
@sunspikes can you please help here?

**Comment by sunspikes** [comment]
If it's sometime working and sometimes not then i guess it has to do with the clamav socket timeout, in case of big files you may have to increase the timeout in clamd.conf otherwise it will fail like you mentioned.

**Comment by khyatiacharya91** [comment]
@sunspikes thanks for response, I'll try it.

**Comment by khyatiacharya91** [comment]
@sunspikes Thanks for reply

**Comment by khyatiacharya91** [comment]
@sunspikes yes, we increases the timeout value in clamd.conf and it's working fine :).
Thanks
