### ISSUE TITLE
Call to undefined method Laravel\Lumen\Application::configPath()

### ISSUE THREAD

**Issue by skarthikeyan2008** [sunspikes/clamav-validator#53]
Call to undefined method Laravel\Lumen\Application::configPath();
in ClamavValidatorServiceProvider.php line 38
In lumen 5.6 , i have this issue

**Comment by sunspikes** [comment]
Looks like this was introduced to Lumen on 6.x, so this should work only for lumen >= 6.0 

https://github.com/laravel/lumen-framework/blob/6.x/src/Application.php#L796

Where as for laravel it was added in 5.4

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Application.php#L333
