### ISSUE TITLE
Access denied Issue - Vagrant Homestead

### ISSUE THREAD

**Issue by jsartisan** [sunspikes/clamav-validator#6]
Hey @sunspikes,

I tried your package. Sadly it does not work on vagrant homestead. Getting access denied.

PFA the screenshot of file permission of UploadedFIle ( phpAPPt0m ) in tmp folder.

![screen shot 2017-02-22 at 1 06 29 pm](https://cloud.githubusercontent.com/assets/6636360/23201512/e441f8a0-f8ff-11e6-9db2-bf230556c529.png)

**Comment by sunspikes** [comment]
Closing as this has nothing to do with the package. Seems to be a ClamAV permission issue. See #5
