### ISSUE TITLE
Laravel 11 not supported

### ISSUE THREAD

**Issue by MrAw3som3** [sunspikes/clamav-validator#70]
Hey there @sunspikes and the other contributors,
first and foremost thank you for this great package.

In my free time today I wanted to wrap my head around updating my projects to Laravel 11 and one of them is using clamav-validator. In this specific project the package is the only one that prevents me from upgrading, so I thought I would ask nicely for this simple change to be made.

I looked at the commit enabling Laravel 10 support by @ashleyshenton and it was "just" updating the composer dependencies.

To not come off as lazy, demanding or unprepared I did my fair share: Cloned this project, updated the composer.json to use the necessary versions of the conflicting packages, implemented it as a local package in my project and tested if anything breaks. I am glad that it still works like a charm for me in my - now - Laravel 11 application.

`"illuminate/support": "~5.0 || ^6.0 || ^7.0 || ^8.0 || ^9.0 || ^10.0 || ^11.0",`
`"illuminate/validation": "~5.0 || ^6.0 || ^7.0 || ^8.0 || ^9.0 || ^10.0 || ^11.0"`

We just need to update these to lines in the composer.json, like the time Laravel 10 support was implemented.

Any heroes out there?

**Comment by sunspikes** [comment]
Thanks, just merged: https://github.com/sunspikes/clamav-validator/pull/71

**Comment by mweber-ion2s** [comment]
Thank you very much for the fast reaction :)
